---

- name: install jupyterhub dependencies via conda
  conda: name={{item}} state=present
  become: true
  with_items:
    - configurable-http-proxy
    - sqlalchemy

- name: install jupyterhub via pip
  pip: name={{item}} state=present editable=false executable=pip
  become: true
  with_items:
    - jupyterhub==0.8.1
    - oauthenticator==0.7.2
