---
# Uses conda to install ipython and jupyter dependencies and python3 kernel

- name: conda install ipython and jupyter deps
  conda: name={{item}} state=present
  become: true
  with_items:
    - notebook=4.2
    - ipyparallel
    - ipykernel
    - nbconvert
    - pandoc
    - ipywidgets=5

- name: install python3 kernelspec
  command: python3 -m IPython kernel install
  become: true
