---

- name: install cull_idle_servers dependencies
  pip: name=python-dateutil state=present

- name: install cull_idle_servers.py into {{jupyterhub_srv_dir}}
  copy: src=cull_idle_servers.py dest={{jupyterhub_srv_dir}} owner=root group=root mode=0700

