---

# This playbook installs common packages used on a UNIX/Linux system

- name: update apt
  apt: update_cache=yes cache_valid_time=3600
  become: yes

# required to upgrade apt
- name: install aptitude
  apt: pkg=aptitude
  become: yes

# upgrade requires aptitude be installed
- name: upgrade apt
  apt: upgrade=safe
  become: yes

- name: install build-essential tools
  apt: pkg=build-essential state=present
  become: true

- name: install other developer tools
  apt: pkg={{item}} state=present
  become: true
  with_items:
    - gfortran
    - git

- name: install user applications
  apt: pkg={{item}} state=present
  become: true
  with_items:
    - vim
    - emacs
    - tree
    - htop

- name: install open-iscsi for cloud block volumes
  apt: pkg=open-iscsi state=present
  become: true
