---

- name: pip install nbgrader
  pip: name={{item}} state=present
  become: true
  with_items:
    # - nbgrader
    - git+https://github.com/jupyter/nbgrader.git@master#egg=nbgrader

- name: make sure /var/log/nbgrader exists
  file: path={{nbgrader_log_dir}}/ state={{item}} owner=root group=root mode=0755
  become: true
  with_items:
    - directory
    - touch

- name: make sure /srv/nbgrader/exchange exists
  file: path={{nbgrader_exchange_dir}}/ state={{item}} owner=root group=root mode=0733
  become: true
  with_items:
    - directory
    - touch

- name: install the nbgrader nbextensions
  command: jupyter nbextension {{item}} --sys-prefix --py nbgrader
  become: true
  with_items:
    - install
    - enable

- name: install the nbgrader serverextension
  command: jupyter serverextension enable --sys-prefix --py nbgrader
  become: true

- name: stat home directories of instructors
  stat: path={{home_dir}}/{{item.owner}}
  with_items:
    - "{{nbgrader_courses}}"
  register: home_dirs_exists

- name: fail if home directories of instructors don't exist
  fail: msg="Instructors' home directory doesn't exist, create them first!"
  when: item.stat.exists == False
  with_items:
    - "{{home_dirs_exists.results}}"

- name: make sure base exists
  file: path={{home_dir}}/{{item[0].owner}}/nbgrader/{{item[0].course_id}}/ state={{item[1]}} owner={{item[0].owner}} group={{item[0].owner}} mode=0700
  become: true
  with_nested:
    - "{{nbgrader_courses}}"
    - ['directory', 'touch']

- name: make sure subdirectories exist
  file: path={{home_dir}}/{{item[0].owner}}/nbgrader/{{item[0].course_id}}/{{item[1]}}/ state=directory owner={{item[0].owner}} group={{item[0].owner}} mode=0700
  become: true
  with_nested:
    - "{{nbgrader_courses}}"
    - ['source', 'release', 'feedback', 'autograded', 'submitted']

- name: install nbgrader config file
  template: src=nbgrader_config.py.j2 dest={{home_dir}}/{{item.owner}}/nbgrader/{{item.course_id}}/nbgrader_config.py owner={{item.owner}} group={{item.owner}} mode=700
  become: true
  with_items:
    - "{{nbgrader_courses}}"

